# Generated by Django 3.1.2 on 2020-10-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_user_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
