# Generated by Django 3.1.2 on 2020-10-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='score',
            new_name='marks',
        ),
    ]
