# Generated by Django 3.1.2 on 2020-10-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201026_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='student_name',
            new_name='user_name',
        ),
    ]
