# Generated by Django 3.1.2 on 2020-10-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201028_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
