# Generated by Django 3.1.2 on 2020-10-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetTimeLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.IntegerField(default=0)),
            ],
        ),
    ]
