# Generated by Django 3.1.2 on 2020-10-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_settimelimit_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='temp_score',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
