# Generated by Django 3.1.2 on 2020-10-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_choice_temp_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='temp_score',
        ),
        migrations.AddField(
            model_name='question',
            name='temp_score',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
