# Generated by Django 3.1.2 on 2020-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_chatbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='chatter_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
